version: 2

models:

  - name: dim_developers
    columns:
      - name: developer_key
        tests:
          - not_null
          - unique

  - name: dim_categories
    columns:
      - name: category_key
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

  - name: dim_apps
    columns:
      - name: app_key
        tests:
          - not_null
          - unique
      - name: developer_key
        tests:
          - relationships:
              to: ref('dim_developers')
              field: developer_key
      - name: category_key
        tests:
          - relationships:
              to: ref('dim_categories')
              field: category_key

  - name: fact_reviews
    columns:
      - name: review_id
        tests:
          - not_null
      - name: app_key
        tests:
          - relationships:
              to: ref('dim_apps')
              field: app_key
      - name: developer_key
        tests:
          - relationships:
              to: ref('dim_developers')
              field: developer_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
